# Generated by Django 5.1.4 on 2025-07-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_profile_image_alter_customuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Eleições SecureVote', max_length=255)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuração da Eleição',
                'verbose_name_plural': 'Configurações da Eleição',
            },
        ),
    ]
