# Generated by Django 5.1.4 on 2025-07-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_electionsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electionsetting',
            options={'verbose_name': 'Configuração Global da Eleição', 'verbose_name_plural': 'Configurações Globais da Eleição'},
        ),
    ]
