# Generated by Django 5.1.4 on 2025-09-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_electionsetting_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="electionsetting",
            name="show_votes",
            field=models.BooleanField(default=True, verbose_name="Mostrar Votos"),
        ),
    ]
