--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9
-- Dumped by pg_dump version 16.9

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_customuser; Type: TABLE; Schema: public; Owner: aquilivio
--

CREATE TABLE public.account_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    user_type character varying(1) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    profile_image character varying(100)
);


ALTER TABLE public.account_customuser OWNER TO aquilivio;

--
-- Name: account_customuser_groups; Type: TABLE; Schema: public; Owner: aquilivio
--

CREATE TABLE public.account_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.account_customuser_groups OWNER TO aquilivio;

--
-- Name: account_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: aquilivio
--

ALTER TABLE public.account_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: aquilivio
--

ALTER TABLE public.account_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_customuser_user_permissions; Type: TABLE; Schema: public; Owner: aquilivio
--

CREATE TABLE public.account_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.account_customuser_user_permissions OWNER TO aquilivio;

--
-- Name: account_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: aquilivio
--

ALTER TABLE public.account_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_electionsetting; Type: TABLE; Schema: public; Owner: aquilivio
--

CREATE TABLE public.account_electionsetting (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    start_time timestamp with time zone,
    end_time timestamp with time zone,
    is_active boolean NOT NULL
);


ALTER TABLE public.account_electionsetting OWNER TO aquilivio;

--
-- Name: account_electionsetting_id_seq; Type: SEQUENCE; Schema: public; Owner: aquilivio
--

ALTER TABLE public.account_electionsetting ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_electionsetting_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: aquilivio
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO aquilivio;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: aquilivio
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: aquilivio
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO aquilivio;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: aquilivio
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: aquilivio
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO aquilivio;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: aquilivio
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: aquilivio
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO aquilivio;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: aquilivio
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: aquilivio
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO aquilivio;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: aquilivio
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: aquilivio
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO aquilivio;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: aquilivio
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: aquilivio
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO aquilivio;

--
-- Name: django_site; Type: TABLE; Schema: public; Owner: aquilivio
--

CREATE TABLE public.django_site (
    id integer NOT NULL,
    domain character varying(100) NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.django_site OWNER TO aquilivio;

--
-- Name: django_site_id_seq; Type: SEQUENCE; Schema: public; Owner: aquilivio
--

ALTER TABLE public.django_site ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_site_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: voting_candidate; Type: TABLE; Schema: public; Owner: aquilivio
--

CREATE TABLE public.voting_candidate (
    id bigint NOT NULL,
    fullname character varying(50) NOT NULL,
    photo character varying(100) NOT NULL,
    bio text NOT NULL,
    position_id bigint NOT NULL
);


ALTER TABLE public.voting_candidate OWNER TO aquilivio;

--
-- Name: voting_candidate_id_seq; Type: SEQUENCE; Schema: public; Owner: aquilivio
--

ALTER TABLE public.voting_candidate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.voting_candidate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: voting_position; Type: TABLE; Schema: public; Owner: aquilivio
--

CREATE TABLE public.voting_position (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    max_vote integer NOT NULL,
    priority integer NOT NULL
);


ALTER TABLE public.voting_position OWNER TO aquilivio;

--
-- Name: voting_position_id_seq; Type: SEQUENCE; Schema: public; Owner: aquilivio
--

ALTER TABLE public.voting_position ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.voting_position_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: voting_voter; Type: TABLE; Schema: public; Owner: aquilivio
--

CREATE TABLE public.voting_voter (
    id bigint NOT NULL,
    phone character varying(11) NOT NULL,
    otp character varying(10),
    verified boolean NOT NULL,
    voted boolean NOT NULL,
    otp_sent integer NOT NULL,
    admin_id bigint NOT NULL
);


ALTER TABLE public.voting_voter OWNER TO aquilivio;

--
-- Name: voting_voter_id_seq; Type: SEQUENCE; Schema: public; Owner: aquilivio
--

ALTER TABLE public.voting_voter ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.voting_voter_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: voting_votes; Type: TABLE; Schema: public; Owner: aquilivio
--

CREATE TABLE public.voting_votes (
    id bigint NOT NULL,
    candidate_id bigint NOT NULL,
    position_id bigint NOT NULL,
    voter_id bigint NOT NULL
);


ALTER TABLE public.voting_votes OWNER TO aquilivio;

--
-- Name: voting_votes_id_seq; Type: SEQUENCE; Schema: public; Owner: aquilivio
--

ALTER TABLE public.voting_votes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.voting_votes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: account_customuser; Type: TABLE DATA; Schema: public; Owner: aquilivio
--

COPY public.account_customuser (id, password, last_login, is_superuser, first_name, last_name, is_staff, is_active, date_joined, email, user_type, created_at, updated_at, profile_image) FROM stdin;
1	pbkdf2_sha256$870000$6gcyGB3lsHtCb85HJWZBbR$/HHh6UASkbpUgfblT71RjhmjVnofLcXAyAk9Z+73H3A=	2025-07-14 21:22:55.141828+02	t	Carlos Patricio	Pando	t	t	2025-07-14 21:22:04.242114+02	carlos@gmail.com	1	2025-07-14 21:22:06.651467+02	2025-07-14 21:24:09.740956+02	profile_pics/Captura_de_ecrã_de_2025-07-11_21-11-33.png
2	pbkdf2_sha256$870000$T4ARtSdgfdamR1rYhfxz7C$6SUoW+FECNjUE8WcVz+y/y0KdZlAJVp/6AQN/FRhTJI=	\N	f	Silva	Bernardo	f	t	2025-07-14 21:48:10.780264+02	silva@gmail.com	2	2025-07-14 21:48:13.657462+02	2025-07-14 21:48:13.657492+02	
\.


--
-- Data for Name: account_customuser_groups; Type: TABLE DATA; Schema: public; Owner: aquilivio
--

COPY public.account_customuser_groups (id, customuser_id, group_id) FROM stdin;
\.


--
-- Data for Name: account_customuser_user_permissions; Type: TABLE DATA; Schema: public; Owner: aquilivio
--

COPY public.account_customuser_user_permissions (id, customuser_id, permission_id) FROM stdin;
\.


--
-- Data for Name: account_electionsetting; Type: TABLE DATA; Schema: public; Owner: aquilivio
--

COPY public.account_electionsetting (id, title, start_time, end_time, is_active) FROM stdin;
1	Eleições SecureVote	\N	\N	f
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: aquilivio
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: aquilivio
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: aquilivio
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add site	6	add_site
22	Can change site	6	change_site
23	Can delete site	6	delete_site
24	Can view site	6	view_site
25	Can add user	7	add_customuser
26	Can change user	7	change_customuser
27	Can delete user	7	delete_customuser
28	Can view user	7	view_customuser
29	Can add Configuração Global da Eleição	8	add_electionsetting
30	Can change Configuração Global da Eleição	8	change_electionsetting
31	Can delete Configuração Global da Eleição	8	delete_electionsetting
32	Can view Configuração Global da Eleição	8	view_electionsetting
33	Can add position	9	add_position
34	Can change position	9	change_position
35	Can delete position	9	delete_position
36	Can view position	9	view_position
37	Can add candidate	10	add_candidate
38	Can change candidate	10	change_candidate
39	Can delete candidate	10	delete_candidate
40	Can view candidate	10	view_candidate
41	Can add voter	11	add_voter
42	Can change voter	11	change_voter
43	Can delete voter	11	delete_voter
44	Can view voter	11	view_voter
45	Can add votes	12	add_votes
46	Can change votes	12	change_votes
47	Can delete votes	12	delete_votes
48	Can view votes	12	view_votes
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: aquilivio
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: aquilivio
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	sites	site
7	account	customuser
8	account	electionsetting
9	voting	position
10	voting	candidate
11	voting	voter
12	voting	votes
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: aquilivio
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-07-14 21:17:17.689483+02
2	contenttypes	0002_remove_content_type_name	2025-07-14 21:17:17.79586+02
3	auth	0001_initial	2025-07-14 21:17:18.464167+02
4	auth	0002_alter_permission_name_max_length	2025-07-14 21:17:18.527497+02
5	auth	0003_alter_user_email_max_length	2025-07-14 21:17:18.588113+02
6	auth	0004_alter_user_username_opts	2025-07-14 21:17:18.646785+02
7	auth	0005_alter_user_last_login_null	2025-07-14 21:17:18.712823+02
8	auth	0006_require_contenttypes_0002	2025-07-14 21:17:18.765911+02
9	auth	0007_alter_validators_add_error_messages	2025-07-14 21:17:18.829564+02
10	auth	0008_alter_user_username_max_length	2025-07-14 21:17:18.889398+02
11	auth	0009_alter_user_last_name_max_length	2025-07-14 21:17:18.952327+02
12	auth	0010_alter_group_name_max_length	2025-07-14 21:17:19.026224+02
13	auth	0011_update_proxy_permissions	2025-07-14 21:17:19.092381+02
14	auth	0012_alter_user_first_name_max_length	2025-07-14 21:17:19.153693+02
15	account	0001_initial	2025-07-14 21:17:20.01546+02
16	account	0002_customuser_profile_image_alter_customuser_id	2025-07-14 21:17:21.262586+02
17	account	0003_electionsetting	2025-07-14 21:17:21.415355+02
18	account	0004_alter_electionsetting_options	2025-07-14 21:17:21.468055+02
19	admin	0001_initial	2025-07-14 21:17:22.14058+02
20	admin	0002_logentry_remove_auto_add	2025-07-14 21:17:22.257766+02
21	admin	0003_logentry_add_action_flag_choices	2025-07-14 21:17:22.331494+02
22	sessions	0001_initial	2025-07-14 21:17:22.750201+02
23	sites	0001_initial	2025-07-14 21:17:22.93231+02
24	sites	0002_alter_domain_unique	2025-07-14 21:17:23.139572+02
25	voting	0001_initial	2025-07-14 21:17:25.242526+02
26	voting	0002_alter_candidate_id_alter_position_id_alter_voter_id_and_more	2025-07-14 21:17:27.856101+02
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: aquilivio
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
qolic9mf8y3pue3yjyie3oqat5b8czyk	.eJxVjM0KwjAQhN8lZynZ_GxSj4LPEXbXlRS1gm1O4rtLoEI9zjffzNsUamstbdFXmS7maMAc9oxJbjr3gkSebV4HfdB0__Hh3NNpk_6WlZba_7xiQPDJqs0OhdFiEIljFJeSqLIHC07tCBxiBi-aIweXEgkwXc3nCwd4NJI:1ubOlL:zSC9gOwFJTf5_TBeb3IoPbMBd3s5tuPKm9dABZpiEBI	2025-07-28 21:22:55.193131+02
\.


--
-- Data for Name: django_site; Type: TABLE DATA; Schema: public; Owner: aquilivio
--

COPY public.django_site (id, domain, name) FROM stdin;
1	example.com	example.com
\.


--
-- Data for Name: voting_candidate; Type: TABLE DATA; Schema: public; Owner: aquilivio
--

COPY public.voting_candidate (id, fullname, photo, bio, position_id) FROM stdin;
\.


--
-- Data for Name: voting_position; Type: TABLE DATA; Schema: public; Owner: aquilivio
--

COPY public.voting_position (id, name, max_vote, priority) FROM stdin;
\.


--
-- Data for Name: voting_voter; Type: TABLE DATA; Schema: public; Owner: aquilivio
--

COPY public.voting_voter (id, phone, otp, verified, voted, otp_sent, admin_id) FROM stdin;
1	8453627727	\N	f	f	0	2
\.


--
-- Data for Name: voting_votes; Type: TABLE DATA; Schema: public; Owner: aquilivio
--

COPY public.voting_votes (id, candidate_id, position_id, voter_id) FROM stdin;
\.


--
-- Name: account_customuser_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aquilivio
--

SELECT pg_catalog.setval('public.account_customuser_groups_id_seq', 1, false);


--
-- Name: account_customuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aquilivio
--

SELECT pg_catalog.setval('public.account_customuser_id_seq', 2, true);


--
-- Name: account_customuser_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aquilivio
--

SELECT pg_catalog.setval('public.account_customuser_user_permissions_id_seq', 1, false);


--
-- Name: account_electionsetting_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aquilivio
--

SELECT pg_catalog.setval('public.account_electionsetting_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aquilivio
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aquilivio
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aquilivio
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 48, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aquilivio
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aquilivio
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 12, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aquilivio
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 26, true);


--
-- Name: django_site_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aquilivio
--

SELECT pg_catalog.setval('public.django_site_id_seq', 1, true);


--
-- Name: voting_candidate_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aquilivio
--

SELECT pg_catalog.setval('public.voting_candidate_id_seq', 1, false);


--
-- Name: voting_position_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aquilivio
--

SELECT pg_catalog.setval('public.voting_position_id_seq', 1, false);


--
-- Name: voting_voter_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aquilivio
--

SELECT pg_catalog.setval('public.voting_voter_id_seq', 1, true);


--
-- Name: voting_votes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: aquilivio
--

SELECT pg_catalog.setval('public.voting_votes_id_seq', 1, false);


--
-- Name: account_customuser account_customuser_email_key; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.account_customuser
    ADD CONSTRAINT account_customuser_email_key UNIQUE (email);


--
-- Name: account_customuser_groups account_customuser_groups_customuser_id_group_id_7e51db7b_uniq; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.account_customuser_groups
    ADD CONSTRAINT account_customuser_groups_customuser_id_group_id_7e51db7b_uniq UNIQUE (customuser_id, group_id);


--
-- Name: account_customuser_groups account_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.account_customuser_groups
    ADD CONSTRAINT account_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: account_customuser account_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.account_customuser
    ADD CONSTRAINT account_customuser_pkey PRIMARY KEY (id);


--
-- Name: account_customuser_user_permissions account_customuser_user__customuser_id_permission_650e378f_uniq; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.account_customuser_user_permissions
    ADD CONSTRAINT account_customuser_user__customuser_id_permission_650e378f_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: account_customuser_user_permissions account_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.account_customuser_user_permissions
    ADD CONSTRAINT account_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: account_electionsetting account_electionsetting_pkey; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.account_electionsetting
    ADD CONSTRAINT account_electionsetting_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: django_site django_site_domain_a2e37b91_uniq; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_domain_a2e37b91_uniq UNIQUE (domain);


--
-- Name: django_site django_site_pkey; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.django_site
    ADD CONSTRAINT django_site_pkey PRIMARY KEY (id);


--
-- Name: voting_candidate voting_candidate_pkey; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.voting_candidate
    ADD CONSTRAINT voting_candidate_pkey PRIMARY KEY (id);


--
-- Name: voting_position voting_position_name_key; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.voting_position
    ADD CONSTRAINT voting_position_name_key UNIQUE (name);


--
-- Name: voting_position voting_position_pkey; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.voting_position
    ADD CONSTRAINT voting_position_pkey PRIMARY KEY (id);


--
-- Name: voting_voter voting_voter_admin_id_key; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.voting_voter
    ADD CONSTRAINT voting_voter_admin_id_key UNIQUE (admin_id);


--
-- Name: voting_voter voting_voter_phone_key; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.voting_voter
    ADD CONSTRAINT voting_voter_phone_key UNIQUE (phone);


--
-- Name: voting_voter voting_voter_pkey; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.voting_voter
    ADD CONSTRAINT voting_voter_pkey PRIMARY KEY (id);


--
-- Name: voting_votes voting_votes_pkey; Type: CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.voting_votes
    ADD CONSTRAINT voting_votes_pkey PRIMARY KEY (id);


--
-- Name: account_customuser_email_a15d8618_like; Type: INDEX; Schema: public; Owner: aquilivio
--

CREATE INDEX account_customuser_email_a15d8618_like ON public.account_customuser USING btree (email varchar_pattern_ops);


--
-- Name: account_customuser_groups_customuser_id_b6c60904; Type: INDEX; Schema: public; Owner: aquilivio
--

CREATE INDEX account_customuser_groups_customuser_id_b6c60904 ON public.account_customuser_groups USING btree (customuser_id);


--
-- Name: account_customuser_groups_group_id_2be9f6d7; Type: INDEX; Schema: public; Owner: aquilivio
--

CREATE INDEX account_customuser_groups_group_id_2be9f6d7 ON public.account_customuser_groups USING btree (group_id);


--
-- Name: account_customuser_user_permissions_customuser_id_03bcc114; Type: INDEX; Schema: public; Owner: aquilivio
--

CREATE INDEX account_customuser_user_permissions_customuser_id_03bcc114 ON public.account_customuser_user_permissions USING btree (customuser_id);


--
-- Name: account_customuser_user_permissions_permission_id_f4aec423; Type: INDEX; Schema: public; Owner: aquilivio
--

CREATE INDEX account_customuser_user_permissions_permission_id_f4aec423 ON public.account_customuser_user_permissions USING btree (permission_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: aquilivio
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: aquilivio
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: aquilivio
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: aquilivio
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: aquilivio
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: aquilivio
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: aquilivio
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: aquilivio
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: django_site_domain_a2e37b91_like; Type: INDEX; Schema: public; Owner: aquilivio
--

CREATE INDEX django_site_domain_a2e37b91_like ON public.django_site USING btree (domain varchar_pattern_ops);


--
-- Name: voting_candidate_position_id_11fc864a; Type: INDEX; Schema: public; Owner: aquilivio
--

CREATE INDEX voting_candidate_position_id_11fc864a ON public.voting_candidate USING btree (position_id);


--
-- Name: voting_position_name_fe5a4e91_like; Type: INDEX; Schema: public; Owner: aquilivio
--

CREATE INDEX voting_position_name_fe5a4e91_like ON public.voting_position USING btree (name varchar_pattern_ops);


--
-- Name: voting_voter_phone_8cb47aeb_like; Type: INDEX; Schema: public; Owner: aquilivio
--

CREATE INDEX voting_voter_phone_8cb47aeb_like ON public.voting_voter USING btree (phone varchar_pattern_ops);


--
-- Name: voting_votes_candidate_id_4f8a611d; Type: INDEX; Schema: public; Owner: aquilivio
--

CREATE INDEX voting_votes_candidate_id_4f8a611d ON public.voting_votes USING btree (candidate_id);


--
-- Name: voting_votes_position_id_2d19ba9a; Type: INDEX; Schema: public; Owner: aquilivio
--

CREATE INDEX voting_votes_position_id_2d19ba9a ON public.voting_votes USING btree (position_id);


--
-- Name: voting_votes_voter_id_f4b66619; Type: INDEX; Schema: public; Owner: aquilivio
--

CREATE INDEX voting_votes_voter_id_f4b66619 ON public.voting_votes USING btree (voter_id);


--
-- Name: account_customuser_groups account_customuser_groups_customuser_id_b6c60904_fk; Type: FK CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.account_customuser_groups
    ADD CONSTRAINT account_customuser_groups_customuser_id_b6c60904_fk FOREIGN KEY (customuser_id) REFERENCES public.account_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_customuser_groups account_customuser_groups_group_id_2be9f6d7_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.account_customuser_groups
    ADD CONSTRAINT account_customuser_groups_group_id_2be9f6d7_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_customuser_user_permissions account_customuser_u_permission_id_f4aec423_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.account_customuser_user_permissions
    ADD CONSTRAINT account_customuser_u_permission_id_f4aec423_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_customuser_user_permissions account_customuser_user_permissions_customuser_id_03bcc114_fk; Type: FK CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.account_customuser_user_permissions
    ADD CONSTRAINT account_customuser_user_permissions_customuser_id_03bcc114_fk FOREIGN KEY (customuser_id) REFERENCES public.account_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_account_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_account_customuser_id FOREIGN KEY (user_id) REFERENCES public.account_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: voting_candidate voting_candidate_position_id_11fc864a_fk; Type: FK CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.voting_candidate
    ADD CONSTRAINT voting_candidate_position_id_11fc864a_fk FOREIGN KEY (position_id) REFERENCES public.voting_position(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: voting_voter voting_voter_admin_id_62ab8e8d_fk_account_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.voting_voter
    ADD CONSTRAINT voting_voter_admin_id_62ab8e8d_fk_account_customuser_id FOREIGN KEY (admin_id) REFERENCES public.account_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: voting_votes voting_votes_candidate_id_4f8a611d_fk; Type: FK CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.voting_votes
    ADD CONSTRAINT voting_votes_candidate_id_4f8a611d_fk FOREIGN KEY (candidate_id) REFERENCES public.voting_candidate(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: voting_votes voting_votes_position_id_2d19ba9a_fk; Type: FK CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.voting_votes
    ADD CONSTRAINT voting_votes_position_id_2d19ba9a_fk FOREIGN KEY (position_id) REFERENCES public.voting_position(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: voting_votes voting_votes_voter_id_f4b66619_fk; Type: FK CONSTRAINT; Schema: public; Owner: aquilivio
--

ALTER TABLE ONLY public.voting_votes
    ADD CONSTRAINT voting_votes_voter_id_f4b66619_fk FOREIGN KEY (voter_id) REFERENCES public.voting_voter(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

